# permissions for end users to edit nodeconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeconfig-editor-role
rules:
- apiGroups:
  - config.snappcloud.io
  resources:
  - nodeconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.snappcloud.io
  resources:
  - nodeconfigs/status
  verbs:
  - get
