---
apiVersion: config.snappcloud.io/v1alpha1
kind: NodeConfig
metadata:
  name: nodeconfig-edge
spec:
  match:
    nodeNamePatterns:
      - okd4-edge-edge-.*
    # nodeSelectorTerms:
    # - matchExpressions:
    #   - key: kubernetes.io/hostname
    #     operator: In
    #     values:
    #     - minikube
    #   - key: beta.kubernetes.io/os
    #     operator: In
    #     values:
    #     - linux
    # - matchExpressions:
    #   - key: another-node-label-key
    #     operator: Exists
  merge:
    labels:
      node-role.kubernetes.io/edge: "true"
    annotations:
      nodeconfig.config.snappcloud.io/managed: "true"
    taints:
    - key: node-role.kubernetes.io/edge
      effect: NoExecute
---
apiVersion: config.snappcloud.io/v1alpha1
kind: NodeConfig
metadata:
  name: nodeconfig-build
spec:
  match:
    nodeNamePatterns:
      - okd4-worker-build
  merge:
    labels:
      node-role.kubernetes.io/build: "true"
    taints:
    -  key: node-role.kubernetes.io/build
       effect: NoExecute
---
apiVersion: config.snappcloud.io/v1alpha1
kind: NodeConfig
metadata:
  name: spare-prefer-taint
spec:
  match:
    nodeNamePatterns:
      - okd4-worker-worker-0
      - okd4-worker-worker-1
  merge:
    taints:
    - key: node-role.kubernetes.io/spare
      effect: PreferNoSchedule

